contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #variantcatalogue channel"
    url: https://nfcore.slack.com/channels/variantcatalogue
    about: Discussion about the nf-core/variantcatalogue pipeline
